### ISSUE TITLE
No ability to create tables

### ISSUE THREAD

**Issue by gglanzani** [Fokko/docker-pyspark#4]
This results in a pesky exception:

```python
> df.write.saveAsTable('test_order')
18/03/23 07:59:51 WARN Persist: Insert of object "org.apache.hadoop.hive.metastore.model.MTable@12988179" using statement "INSERT INTO TBLS (TBL_ID,SD_ID,TBL_NAME,LAST_ACCESS_TIME,RETENTION,VIEW_EXPANDED_TEXT,DB_ID,VIEW_ORIGINAL_TEXT,CREATE_TIME,OWNER,TBL_TYPE) VALUES (?,?,?,?,?,?,?,?,?,?,?)" failed : Java exception: ': java.lang.NullPointerException'.
18/03/23 07:59:51 ERROR Transaction: Operation rollback failed on resource: org.datanucleus.store.rdbms.ConnectionFactoryImpl$EmulatedXAResource@1e832478, error code UNKNOWN and transaction: [DataNucleus Transaction, ID=Xid=���\, enlisted resources=[org.datanucleus.store.rdbms.ConnectionFactoryImpl$EmulatedXAResource@1e832478]]
```
Are there extra things that needs to be installed/done on the image creation?

I think we could maybe build Spark from sources so that we can add hive support:

```
./build/mvn -Pyarn -Phive -Phive-thriftserver -DskipTests clean package
```

@bbrumi just built a Dockerfile with Spark and Hive support (although for an older Spark version). Maybe she can chime in?

**Comment by Fokko** [comment]
Are you sure this isn't a bug. A nullpointerexception could be everything.

**Comment by gglanzani** [comment]
@Fokko I also get it with this

```python
spark.sql('create table test (a int)')
```

I don't think that's a bug (🐛 🐞). How would it get past testing?

I think it has to do with Hive support

**Comment by gglanzani** [comment]
(You can try if you log in in your Docker image)

**Comment by Fokko** [comment]
```
scala> spark.sql("create table this_works_giovanni (a int)").collect()
18/03/23 08:30:32 WARN HiveMetaStore: Location: file:/usr/spark-warehouse/this_works_giovanni specified for non-external table:this_works_giovanni
res2: Array[org.apache.spark.sql.Row] = Array()
```

**Comment by Fokko** [comment]
I've updated the image, to get rid of Oracle JVM. This will make @nielszeilemaker happy. The previous image had Python 3.6, this one ships with 3.5, is this ok?

**Comment by NielsZeilemaker** [comment]
@Fokko see https://github.com/godatadriven-dockerhub/pyspark for my version of a pyspark docker container

**Comment by gglanzani** [comment]
@NielsZeilemaker @Fokko I confirm that the pyspark GDD image works :)
